# CREDIT CARD FRAUD TRANSACTION DETECTION MODEL

TECHNOHACKS EDUTECH OFFICIAL INTERNSHIP PROGRAM:
(Batch july 2023)

**Author: Avanti Ashok Bhondwe**

Problem Statement: Use a dataset of credit card transactions and
build a model that can identify potentially
fraudulent transactions

IMPORTING LIBARIES:

In [52]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
file_path = '/content/creditcard.csv'
credit_card_data = pd.read_csv(file_path)

In [4]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [5]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
3968,3617,1.134592,0.252051,0.488592,0.799826,-0.264819,-0.369918,-0.243365,0.049761,1.210818,...,-0.351115,-0.851463,0.186169,0.092463,0.020015,0.057976,-0.046611,0.012562,13.99,0.0
3969,3621,-1.338671,1.080974,1.291196,0.719258,0.101320,0.053896,0.001297,-0.917575,1.638510,...,0.498030,-0.483932,0.037686,0.053566,-0.560078,0.230423,-0.119911,0.321847,27.43,0.0
3970,3622,-0.339728,-2.417449,0.975517,2.537995,-1.720361,0.863005,0.032965,0.026764,2.487139,...,0.391639,0.264432,-0.735031,0.450594,0.310022,-0.231357,-0.049872,0.153526,730.32,0.0
3971,3623,-0.368639,0.947432,1.707755,0.932092,0.292956,0.189100,0.499330,0.132466,0.779412,...,-0.119045,0.056665,-0.172703,0.170073,0.139605,-0.420518,0.033794,0.005996,6.87,0.0
3972,3624,-0.663445,1.162921,1.508050,0.549405,0.231377,-0.106041,0.817977,-0.387026,1.488054,...,-0.420337,-0.361357,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3973 entries, 0 to 3972
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    3973 non-null   int64
 1   V1      3973 non-null   float64
 2   V2      3973 non-null   float64
 3   V3      3973 non-null   float64
 4   V4      3973 non-null   float64
 5   V5      3973 non-null   float64
 6   V6      3973 non-null   float64
 7   V7      3973 non-null   float64
 8   V8      3973 non-null   float64
 9   V9      3973 non-null   float64
 10  V10     3973 non-null   float64
 11  V11     3973 non-null   float64
 12  V12     3973 non-null   float64
 13  V13     3973 non-null   float64
 14  V14     3973 non-null   float64
 15  V15     3973 non-null   float64
 16  V16     3973 non-null   float64
 17  V17     3973 non-null   float64
 18  V18     3973 non-null   float64
 19  V19     3973 non-null   float64
 20  V20     3973 non-null   float64
 21  V21     3973 non-null   float64
 22  V22     3973 non-null   float64
 23  V23     3972 non-null   float64
 24  V24     3972 non-null   float64
 25  V25     3972 non-null   float64
 26  V26     3972 non-null   float64
 27  V27     3972 non-null   float64
 28  V28     3972 non-null   float64
 29  Amount  3972 non-null   float64
 30  Class   3972 non-null   float64
dtypes: float64(30), int64(1)
memory usage: 962.3 KB

In [53]:
credit_card_data.isnull().sum()

Time       0
V1         0
V2         0
V3         0
V4         0
V5         0
V6         0
V7         0
V8         0
V9         0
V10        0
V11        0
V12        0
V13        0
V14        0
V15        0
V16        0
V17        0
V18        0
V19        0
V20        0
V21        0
V22        0
V23        0
V24        0
V25        0
V26        0
V27        0
V28        0
Amount     0
Class      0
Anomaly    0
dtype: int64

*We are having null values replace it my mean using fillna*

In [8]:
credit_card_data.fillna(credit_card_data.mean(), inplace=True)

In [9]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

BINARY CLASSIFICATION

After making these adjustments, you should have a 'Class' column with only binary values (0 or 1), where 0 represents non-fraudulent transactions, and 1 represents fraudulent transactions.

In [10]:
credit_card_data['Class'] = credit_card_data['Class'].astype(int)
credit_card_data = credit_card_data[(credit_card_data['Class'] == 0) | (credit_card_data['Class'] == 1)]

In [11]:
credit_card_data['Class'].value_counts()

0    3971
1       2
Name: Class, dtype: int64

HIGHLY UNBALANCED DATA

In [12]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [13]:
print(legit.shape)
print(fraud.shape)

(3971, 31)
(2, 31)

In [14]:
# statistical measures of the data
legit.Amount.describe()

count    3971.000000
mean       64.899622
std       213.585665
min         0.000000
25%         2.270000
50%        12.990000
75%        54.990000
max      7712.430000
Name: Amount, dtype: float64

In [15]:
fraud.Amount.describe()

count      2.000000
mean     264.500000
std      374.059487
min        0.000000
25%      132.250000
50%      264.500000
75%      396.750000
max      529.000000
Name: Amount, dtype: float64

In [16]:
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,1639.328381,-0.332543,0.309150,0.837615,0.011568,-0.029403,0.053490,0.147526,-0.071721,0.056572,...,0.059639,0.010174,-0.083028,-0.058743,0.029114,0.095244,-0.012637,0.044658,0.002668,64.899622
1,439.000000,-2.677884,-0.602658,-0.260694,3.143275,0.418809,-1.245684,-1.105907,0.661932,-1.520521,...,1.114625,0.589464,0.200214,0.455377,0.013198,0.162159,0.016239,0.004186,-0.053756,264.500000

TRY TO BALANCE DATASET:

*Isolation Forest is a powerful tool for anomaly (Outliers) detection *

In [17]:
import pandas as pd
from sklearn.ensemble import IsolationForest

# Separate the features (X) and target (y)
X = credit_card_data.drop('Class', axis=1)
y = credit_card_data['Class']

# Instantiate the Isolation Forest model
isolation_forest = IsolationForest(contamination='auto', random_state=42)

# Fit the model to the data
isolation_forest.fit(X)

# Predict outliers (fraudulent transactions)
y_pred = isolation_forest.predict(X)

# Convert predictions to binary labels (1 for inliers, -1 for outliers)
y_pred_labels = [1 if p == 1 else 0 for p in y_pred]

# Combine the predicted labels with the original data for further analysis
credit_card_data['Anomaly'] = y_pred_labels

In [18]:
# Separate the data into legitimate (non-fraudulent) and potential fraudulent transactions
legit_transactions = credit_card_data[credit_card_data['Anomaly'] == 1]
potential_fraud_transactions = credit_card_data[credit_card_data['Anomaly'] == 0]

In [19]:
print("Shape of legit_transactions:", legit_transactions.shape)
print("Shape of potential_fraud_transactions:", potential_fraud_transactions.shape)

Shape of legit_transactions: (3779, 32)
Shape of potential_fraud_transactions: (194, 32)

DATA AUGMENTATION:

In [20]:
import pandas as pd
import numpy as np
from imblearn.under_sampling import RandomUnderSampler
# Separate the features (X) and target (y) for both legit and potential fraud transactions
X_legit = legit_transactions.drop('Class', axis=1)
y_legit = legit_transactions['Class']

X_fraud = potential_fraud_transactions.drop('Class', axis=1)
y_fraud = potential_fraud_transactions['Class']
desired_fraud_samples = 300
additional_fraud_samples_needed = desired_fraud_samples - len(X_fraud)

# Create additional samples through data augmentation (example: random perturbations)
augmented_fraud_samples = []
for _ in range(additional_fraud_samples_needed):
    random_idx = np.random.randint(0, len(X_fraud))
    new_sample = X_fraud.iloc[random_idx].copy()
    new_sample += np.random.normal(0, 0.01, len(new_sample))
    augmented_fraud_samples.append(new_sample)

# Convert the augmented samples list to a DataFrame
augmented_fraud_transactions = pd.DataFrame(augmented_fraud_samples, columns=X_fraud.columns)

In [21]:
print(augmented_fraud_transactions.shape)

(106, 31)

In [22]:
legit_sample = legit.sample(n=217)
augmented_fraud_transactions['Class'] = 1

In [23]:
balanced_dataset = pd.concat([legit_sample, augmented_fraud_transactions], ignore_index=True)

In [24]:
print(legit_sample.head())

      Time        V1        V2        V3        V4        V5        V6  \
3053  2616 -1.100953  0.676653  2.717105 -0.649148 -0.391919  0.299520
1754  1356 -0.708659  1.360573  0.704554 -0.103319  0.069847 -0.728133
3222  2794 -0.459109  0.570445  1.166147 -2.145477  0.257543 -0.842267
3442  2937 -0.458856  0.595401  1.173309 -2.148824  0.288287 -0.834071
1339  1046 -1.792545  0.068441  0.802953 -0.541977  0.822320 -0.873966

            V7        V8        V9  ...       V21       V22       V23  \
3053  0.139501  0.316178  0.522965  ...  0.086947  0.618824 -0.338911
1754  0.723974  0.171746 -0.845246  ... -0.340823 -1.181941  0.202594
3222  0.952155 -0.132514  0.657459  ...  0.145480  0.764352 -0.245735
3442  0.975526 -0.152084  0.605299  ...  0.149441  0.792564 -0.249870
1339  0.203552  0.126643  0.202998  ... -0.218152 -0.560770 -0.223479

           V24       V25       V26       V27       V28  Amount  Class
3053  0.233957  0.247763  0.491452  0.214194 -0.050009    3.00      0
1754 -0.142191 -0.684229 -0.221155 -0.139790  0.083403   26.59      0
3222  0.211536 -0.079599 -0.837597  0.247430 -0.026640    1.00      0
3442  0.220968 -0.067943 -0.838752  0.249682 -0.025900    1.00      0
1339 -0.396234 -0.115364  0.285137 -0.285946 -0.024595    1.00      0

[5 rows x 31 columns]

In [25]:
print(augmented_fraud_transactions.head())

             Time         V1         V2        V3        V4         V5  \
2249  1785.990451  -2.273019  -1.554987  1.068470 -0.500160   0.266077
2464  2028.990623 -12.185575 -15.733199 -0.394774  3.794661  10.649286
290    208.996731  -5.848010   5.279790 -1.752553 -1.449341  -1.005158
2520  2091.009653  -3.674753   2.754034  0.300490 -2.372009  -0.161413
2678  2217.005130  -3.017839   2.203876  0.661741 -2.475146  -0.651615

            V6        V7        V8        V9  ...       V22       V23  \
2249 -1.410089 -0.553779 -0.195721  0.108054  ... -0.460073  0.135207
2464 -7.487005 -6.913950  1.561333  0.056284  ... -0.898808  0.015278
290  -0.690819  0.074307  0.772579  3.584842  ... -1.211539  0.215661
2520 -0.711375  1.287456 -0.671993  3.757964  ... -0.697164 -0.190173
2678 -0.101964 -0.140774 -1.719691  1.303196  ... -0.501979  0.022596

           V24       V25       V26       V27       V28      Amount   Anomaly  \
2249  0.388980 -0.652120  0.052887 -0.640929  0.973708   11.533001 -0.001221
2464 -0.093148 -0.351405  0.227747  0.198380 -2.358894  120.002289  0.016168
290  -0.486408  1.124185  0.221573  2.473547  1.588659    8.977318  0.017117
2520 -0.514502  0.383286  0.729043  1.148656  0.391244   38.448303  0.007532
2678 -0.072526  0.684078 -0.378627  1.096580  0.348696    0.998402  0.006791

      Class
2249      1
2464      1
290       1
2520      1
2678      1

[5 rows x 32 columns]

In [26]:
balanced_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V22,V23,V24,V25,V26,V27,V28,Amount,Class,Anomaly
0,2616.0,-1.100953,0.676653,2.717105,-0.649148,-0.391919,0.299520,0.139501,0.316178,0.522965,...,0.618824,-0.338911,0.233957,0.247763,0.491452,0.214194,-0.050009,3.00,0,NaN
1,1356.0,-0.708659,1.360573,0.704554,-0.103319,0.069847,-0.728133,0.723974,0.171746,-0.845246,...,-1.181941,0.202594,-0.142191,-0.684229,-0.221155,-0.139790,0.083403,26.59,0,NaN
2,2794.0,-0.459109,0.570445,1.166147,-2.145477,0.257543,-0.842267,0.952155,-0.132514,0.657459,...,0.764352,-0.245735,0.211536,-0.079599,-0.837597,0.247430,-0.026640,1.00,0,NaN
3,2937.0,-0.458856,0.595401,1.173309,-2.148824,0.288287,-0.834071,0.975526,-0.152084,0.605299,...,0.792564,-0.249870,0.220968,-0.067943,-0.838752,0.249682,-0.025900,1.00,0,NaN
4,1046.0,-1.792545,0.068441,0.802953,-0.541977,0.822320,-0.873966,0.203552,0.126643,0.202998,...,-0.560770,-0.223479,-0.396234,-0.115364,0.285137,-0.285946,-0.024595,1.00,0,NaN

In [27]:
balanced_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V22,V23,V24,V25,V26,V27,V28,Amount,Class,Anomaly
318,720.987509,-3.567043,3.039895,1.024981,-2.438432,-0.045631,-0.918219,1.692132,-1.392025,4.045286,...,-0.205770,-0.087954,0.508243,0.215028,0.474027,-0.290666,-1.125181,1.454750,1,-0.005817
319,87.003906,-5.099828,1.900184,-3.445220,-1.254530,-5.513201,2.101337,3.343013,1.239997,0.263391,...,-0.673964,-0.557454,-0.781600,0.070144,0.761405,0.733622,-0.853882,919.598403,1,0.000641
320,639.994606,-2.224548,1.360897,2.020010,0.820400,0.258600,0.597365,2.657272,-2.443601,2.274579,...,0.351999,-0.488551,0.416004,-0.332834,-0.674048,-3.533548,-1.294756,125.860197,1,0.015633
321,2506.991547,-6.180519,5.035465,-2.730388,-0.942052,-6.657428,5.423956,-9.193626,-22.573163,-3.253881,...,4.390061,1.929386,0.856800,-1.339227,-0.712614,-0.222184,0.068836,544.618761,1,-0.014880
322,1630.994835,-3.990876,2.997146,-0.289636,-0.782763,-1.377442,1.759541,-2.492341,-6.895472,0.133892,...,-2.679439,1.165838,-0.072407,-0.075583,0.387626,0.198209,-0.108673,79.000990,1,0.001232

BALANCED THE DATASET APRROXIMATELY:

In [54]:
balanced_dataset['Class'].value_counts()

0    217
1    106
Name: Class, dtype: int64

In [29]:
balanced_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Anomaly
Class,,,,,,,,,,,,,,,,,,,,,
0,1782.668203,-0.333387,0.311918,0.866132,-0.192063,0.082217,-0.001216,0.196809,-0.099560,0.092379,...,0.070944,-0.030953,-0.029766,-0.033979,0.046372,-0.022731,0.051663,-0.000705,50.949171,NaN
1,1530.668835,-2.563056,0.674092,-0.231135,-0.074747,-0.120265,0.719647,-0.372086,-2.808719,0.803710,...,0.202286,-0.240498,0.149628,-0.078134,0.054562,-0.011218,0.067317,-0.163961,246.567936,0.001953

In [30]:
X = balanced_dataset.drop(columns='Class', axis=1)
Y = balanced_dataset['Class']

In [31]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
0    2616.000000 -1.100953  0.676653  2.717105 -0.649148 -0.391919  0.299520
1    1356.000000 -0.708659  1.360573  0.704554 -0.103319  0.069847 -0.728133
2    2794.000000 -0.459109  0.570445  1.166147 -2.145477  0.257543 -0.842267
3    2937.000000 -0.458856  0.595401  1.173309 -2.148824  0.288287 -0.834071
4    1046.000000 -1.792545  0.068441  0.802953 -0.541977  0.822320 -0.873966
..           ...       ...       ...       ...       ...       ...       ...
318   720.987509 -3.567043  3.039895  1.024981 -2.438432 -0.045631 -0.918219
319    87.003906 -5.099828  1.900184 -3.445220 -1.254530 -5.513201  2.101337
320   639.994606 -2.224548  1.360897  2.020010  0.820400  0.258600  0.597365
321  2506.991547 -6.180519  5.035465 -2.730388 -0.942052 -6.657428  5.423956
322  1630.994835 -3.990876  2.997146 -0.289636 -0.782763 -1.377442  1.759541

           V7         V8        V9  ...        V21       V22       V23  \
0    0.139501   0.316178  0.522965  ...   0.086947  0.618824 -0.338911
1    0.723974   0.171746 -0.845246  ...  -0.340823 -1.181941  0.202594
2    0.952155  -0.132514  0.657459  ...   0.145480  0.764352 -0.245735
3    0.975526  -0.152084  0.605299  ...   0.149441  0.792564 -0.249870
4    0.203552   0.126643  0.202998  ...  -0.218152 -0.560770 -0.223479
..        ...        ...       ...  ...        ...       ...       ...
318  1.692132  -1.392025  4.045286  ...  -0.848457 -0.205770 -0.087954
319  3.343013   1.239997  0.263391  ...  -0.856536 -0.673964 -0.557454
320  2.657272  -2.443601  2.274579  ...  -0.268508  0.351999 -0.488551
321 -9.193626 -22.573163 -3.253881  ... -11.238009  4.390061  1.929386
322 -2.492341  -6.895472  0.133892  ...   7.595834 -2.679439  1.165838

          V24       V25       V26       V27       V28      Amount   Anomaly
0    0.233957  0.247763  0.491452  0.214194 -0.050009    3.000000       NaN
1   -0.142191 -0.684229 -0.221155 -0.139790  0.083403   26.590000       NaN
2    0.211536 -0.079599 -0.837597  0.247430 -0.026640    1.000000       NaN
3    0.220968 -0.067943 -0.838752  0.249682 -0.025900    1.000000       NaN
4   -0.396234 -0.115364  0.285137 -0.285946 -0.024595    1.000000       NaN
..        ...       ...       ...       ...       ...         ...       ...
318  0.508243  0.215028  0.474027 -0.290666 -1.125181    1.454750 -0.005817
319 -0.781600  0.070144  0.761405  0.733622 -0.853882  919.598403  0.000641
320  0.416004 -0.332834 -0.674048 -3.533548 -1.294756  125.860197  0.015633
321  0.856800 -1.339227 -0.712614 -0.222184  0.068836  544.618761 -0.014880
322 -0.072407 -0.075583  0.387626  0.198209 -0.108673   79.000990  0.001232

[323 rows x 31 columns]

In [32]:
print(Y)

0      0
1      0
2      0
3      0
4      0
      ..
318    1
319    1
320    1
321    1
322    1
Name: Class, Length: 323, dtype: int64

DEALING WITH NaN VALUES:

In [33]:
from sklearn.impute import SimpleImputer
# Instantiate the SimpleImputer with a strategy to fill missing values with the mean
imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(X)

In [34]:
X_train, X_test, Y_train, Y_test = train_test_split(X_imputed, Y, test_size=0.2, stratify=Y, random_state=2)

In [35]:
print(X.shape, X_train.shape, X_test.shape)

(323, 31) (258, 31) (65, 31)

LOGISTIC REGRESSION :

*data contains NaN values in the Anomaly column of X,Logistic regression does not accept missing values encoded as NaN natively, and it's important to handle missing values before training the model so ...
Imputation: If dropping rows is not suitable, you can impute the missing values using various techniques.*

In [36]:
model = LogisticRegression()

In [50]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
scaler = StandardScaler()
# Fit and transform the scaler on X_train
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
model = LogisticRegression(max_iter=1000)
# Fit the model to the scaled training data
model.fit(X_train_scaled, Y_train)

LogisticRegression(max_iter=1000)

In [38]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [55]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.7015503875968992

70% ACCURACY BY LOGISTIC REGRESSION FOR TRAINING

In [40]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [56]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.6923076923076923

69% ACCURACY ON TEST DATA

#Random Forest


*Random Forest is generally more robust to overfitting compared to a single decision tree or linear models like logistic regression.*

In [57]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Assuming you have X_train_scaled, X_test_scaled, Y_train, and Y_test as your training and testing data

# Instantiate the Random Forest Classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the classifier on the training data
rf_classifier.fit(X_train_scaled, Y_train)

# Make predictions on the test data
Y_pred = rf_classifier.predict(X_test_scaled)

# Evaluate the model's performance
accuracy = accuracy_score(Y_test, Y_pred)
print("Accuracy:", accuracy)

# Get other evaluation metrics like classification report and confusion matrix
print(classification_report(Y_test, Y_pred))
print(confusion_matrix(Y_test, Y_pred))

Accuracy: 0.9538461538461539
              precision    recall  f1-score   support

           0       1.00      0.93      0.96        44
           1       0.88      1.00      0.93        21

    accuracy                           0.95        65
   macro avg       0.94      0.97      0.95        65
weighted avg       0.96      0.95      0.95        65

[[41  3]
 [ 0 21]]

ACCURACY INCREASED TO 95%